//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battleship
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBBoardConstant
    {
        public int Id { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Constant { get; set; }
    }
}
