//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battleship
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBBoard
    {
        public DBBoard()
        {
            this.DBBoardConstant = new HashSet<DBBoardConstant>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<DBBoardConstant> DBBoardConstant { get; set; }
    }
}
