//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battleship
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBBoardValue
    {
        public int Id { get; set; }
        public int DBBoardId { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public int value { get; set; }
    }
}
