//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battleship
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBGame
    {
        public int Id { get; set; }
    
        public virtual DBPlayer Player1 { get; set; }
        public virtual DBPlayer Player2 { get; set; }
    }
}
